
DELETE http://localhost:4003/db/gifs/new_gif
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjIyYmNlNWY5NTJlMTkzM2RhZDJkYiIsInVzZXJuYW1lIjoic2ViYXNnZWNrbyIsImlhdCI6MTY2MzIyMzk0Mn0.4U9HS_6GPBLSu9Fw2D1OXQEZK4vZ9lvdIce4qTPMuR0
