###
GET http://localhost:4003/db/gifs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDJjNTRjZGU0YzBkMDI3YzgzMTc0OSIsInVzZXJuYW1lIjoic2ViYXNnZWNrbyIsImlhdCI6MTY2MTEzMTUxNX0.V042sOq577j8IDaLOHYcTa80OwkTOkoFG2JkF9E4IwY


###
DELETE  http://localhost:4003/db/gifs/QCxz3P2mDW6HwYIKgr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDJjNTRjZGU0YzBkMDI3YzgzMTc0OSIsInVzZXJuYW1lIjoic2ViYXNnZWNrbyIsImlhdCI6MTY2MTEzMTUxNX0.V042sOq577j8IDaLOHYcTa80OwkTOkoFG2JkF9E4IwY
